name: grpc_protobuf_convert
description: Simple converters to convert to / from Protobuf and Fixnum classes from Dart classes.
version: 1.0.0+1
homepage: https://github.com/peiffer-innovations/grpc_protobuf_convert

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  grpc_googleapis: ^1.0.12

dev_dependencies:
  test: ^1.18.2
