name: 'grpc_protobuf_convert'
description: 'Simple converters to convert to / from Protobuf and Fixnum classes from Dart classes.'
version: '2.0.2+2'
homepage: 'https://github.com/peiffer-innovations/grpc_protobuf_convert'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  fixnum: '^1.1.0'
  grpc_googleapis: '^2.0.32'

dev_dependencies: 
  test: '^1.24.5'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
