name: Dart Pull Request Checker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1.1.1
        with:
          flutter_package: false
